# Generated by Django 4.2.3 on 2023-07-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Numero')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código de barra')),
            ],
            options={
                'verbose_name': 'Llave',
                'verbose_name_plural': 'Llaves',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Código de barra')),
            ],
            options={
                'verbose_name_plural': 'Personales',
            },
        ),
        migrations.CreateModel(
            name='KeyReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de barra de la Llave')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_track_app.key', verbose_name='Llave')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_track_app.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Recepción de Llave',
                'verbose_name_plural': 'Recepción',
            },
        ),
        migrations.CreateModel(
            name='KeyHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de barra del Personal')),
                ('key_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código de barra de la Llave')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_track_app.key', verbose_name='Llave')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_track_app.personal', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Entrega de Llave',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
