# Generated by Django 4.2.3 on 2023-07-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0002_alter_keyhandover_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='last_name',
        ),
    ]
