# Generated by Django 4.2.3 on 2023-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0003_remove_personal_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='document_number',
            field=models.CharField(default=0, max_length=255, verbose_name='Cédula'),
            preserve_default=False,
        ),
    ]
