# Generated by Django 4.2.3 on 2023-07-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0004_personal_document_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keyhandover',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pendiente')), fields=('personal', 'key'), name='unique_pending_key_handover'),
        ),
    ]
