# Generated by Django 4.2.3 on 2023-07-21 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0006_alter_personal_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='document_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[0-9]{6,8} ?[A-Z]{2,3}$')], verbose_name='Cédula'),
        ),
    ]
