# Generated by Django 4.2.3 on 2023-07-21 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0007_alter_personal_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='document_number',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^[\\d.-]+$')], verbose_name='Cédula'),
        ),
    ]
