# Generated by Django 4.2.3 on 2023-07-21 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_track_app', '0008_alter_personal_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(regex='^[\\d.-]+$')], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Teléfono'),
        ),
    ]
